name: generate-breakout-game-from-github-contribution-graph

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Breakout Game
        uses: cyprieng/github-breakout@v1.2.4

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Breakout Game"
          git push
