- name: generate-breakout-game-from-github-contribution-graph
  uses: cyprieng/github-breakout@v1
  with:
    github_username: Luife-correia
    github_token: ${{ secrets.GITHUB_TOKEN }}
    output_path: output/github-contribution-breakout.svg
    enable_ghost_bricks: true
    paddle_color: "#00ffcc"
    ball_color: "#ff0066"
    bricks_colors: "#ffcc00,#ff6600,#00ccff"

          
