            - name: generate-breakout-game-from-github-contribution-graph
  # You may pin to the exact commit or the version.
  # uses: cyprieng/github-breakout@60c43dca3a1361fbc9fb9bb533b5193296345c4f
  uses: cyprieng/github-breakout@60c43dca3a1361fbc9fb9bb533b5193296345c4f
  with:
    # Github username
    github_username: Luife-correia 
    # Github token used to fetch the contributions. Default to the action token if empty.
    github_token: ${{ secrets.GITHUB_TOKEN }}
    # Ghost bricks for days without contribution
    enable_ghost_bricks: true
    # Output path for SVGs
    output_path: # optional
    # Paddle color
    paddle_color: # optional
    # Ball color
    ball_color: # optional
    # Bricks colors
    bricks_colors: # optional
          
